import{a as w,S,i as a}from"./assets/vendor-C4-ZuMk8.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const L="46865368-ded5de9c0791206e82b93b274",q="https://pixabay.com/api/",p=async(r,t=1,n=15)=>{try{return(await w.get(q,{params:{key:L,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:n,page:t}})).data}catch(s){throw console.log("Error fetching images:",s),s}},v=document.querySelector(".gallery"),C=new S(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250,animationSpeed:300,overlay:!0,overlayOpacity:.5});function g(r){const t=r.map(({webformatURL:n,largeImageURL:s,tags:e,likes:o,views:c,comments:h,downloads:b})=>`<li class="gallery-item">
//     <a class="gallery-link" href="${s}">
//       <img class="gallery-img" src="${n}" alt="${e}"  />
//       <div class="gallery-img-info">
//          <p class="info-item-title"><b>Likes</b>${o}</p>
//           <p class="info-item-title"><b>Views</b>${c}</p>
//           <p class="info-item-title"><b>Comments</b>${h}</p>
//           <p class="info-item-title"><b>Downloads</b>${b}</p>
         
//         </div>
//     </a>
//   </li>`).join("");v.insertAdjacentHTML("beforeend",t),C.refresh()}const f=document.querySelector(".search-form");document.querySelector(".loader");const m=document.querySelector(".gallery");document.querySelector(".text-input");const d=document.querySelector(".loader-container"),i=document.querySelector(".load-more-btn");let u="",l=1,y=15;f.addEventListener("submit",O);i.addEventListener("click",E);async function O(r){if(r.preventDefault(),m.innerHTML="",u=r.currentTarget.elements.input.value,u.trim()===""){a.warning({title:"Missing tags",message:"Please enter a search query!",closeOnClick:!0});return}l=1,i.style.display="none",d.style.display="block";try{const t=await p(u,l,y);t.hits.length===0?a.error({title:"No pictures found",message:"Sorry, there are no images matching your search query. Please try again.",timeout:2500,closeOnClick:!0}):(g(t.hits),t.totalHits>y*l?i.style.display="block":(i.style.display="none",a.show({class:"toast",position:"topRight",messageColor:"white",message:"We're sorry, but you've reached the end of search results."})))}catch(t){console.log(t),a.error({title:"Error",message:"Failed to fetch images. Please try again later.",timeout:2500,closeOnClick:!0})}finally{d.style.display="none"}f.reset()}async function E(){d.style.display="block",l+=1;try{const r=await p(u,l,y);g(r.hits),console.log(m.lastElementChild);const t=m.lastElementChild.getBoundingClientRect();window.scrollBy({top:t.top+t.height*1.5,behavior:"smooth"}),r.totalHits>y*l?i.style.display="block":(i.style.display="none",a.show({class:"toast",position:"topRight",messageColor:"white",message:"We are sorry, there are no more posts to load"}))}catch(r){console.log(r),a.error({title:"Error",message:"Failed to fetch images. Please try again later.",timeout:2500,closeOnClick:!0})}finally{d.style.display="none"}}
//# sourceMappingURL=index.js.map
